=== UICrail/SemanticRSM/Source_data/scheibenberg/eng.xsd
<?xml version="1.0" ?>
<xs:schema targetNamespace="https://erju.org/eng" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eng="https://erju.org/eng" elementFormDefault="qualified" xmlns:infra="https://erju.org/infra" xmlns:ss026="https://erju.org/ss026">
	<xs:import namespace="https://erju.org/infra" schemaLocation="infra.xsd"/>
	<xs:import namespace="https://erju.org/ss026" schemaLocation="ss026.xsd"/>
	<xs:simpleType name="BufferStopType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="friction"/>
			<xs:enumeration value="hydraulic"/>
			<xs:enumeration value="fixated"/>
			<xs:enumeration value="other"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DuplicationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="noDuplicates"/>
			<xs:enumeration value="duplicateNextBalise"/>
			<xs:enumeration value="duplicatePreviousBalise"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SleepersType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="unknownSleepersType"/>
			<xs:enumeration value="composite"/>
			<xs:enumeration value="concrete"/>
			<xs:enumeration value="steel"/>
			<xs:enumeration value="wood"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="BufferStop">
		<xs:sequence>
			<xs:element name="dangerPoints" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to eng:DangerPoint</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dangerPoint" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="trackEdgeSections" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="trackEdgeSection" type="infra:TrackEdgeSection" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="bsType" type="eng:BufferStopType" use="required"/>
	</xs:complexType>
	<xs:element name="bufferStop" type="eng:BufferStop"/>
	<xs:complexType name="SimplePoint">
		<xs:sequence>
			<xs:element name="foulingPoints" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to eng:FoulingPoint</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="foulingPoint" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="tipShift" type="xs:decimal" use="required"/>
		<xs:attribute name="bladeLength" type="xs:decimal" use="required"/>
	</xs:complexType>
	<xs:element name="simplePoint" type="eng:SimplePoint"/>
	<xs:complexType name="Crossing">
		<xs:sequence>
			<xs:element name="foulingPoints" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to eng:FoulingPoint</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="foulingPoint" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="crossing" type="eng:Crossing"/>
	<xs:complexType name="LevelCrossing">
		<xs:sequence>
			<xs:element name="dangerPoints" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to eng:DangerPoint</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dangerPoint" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="levelCrossing" type="eng:LevelCrossing"/>
	<xs:complexType name="BaliseGroup">
		<xs:sequence/>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="m_version" type="ss026:ETCSVersion" use="required"/>
		<xs:attribute name="q_link" type="xs:boolean" use="required"/>
		<xs:attribute name="q_updown" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:element name="baliseGroup" type="eng:BaliseGroup"/>
	<xs:complexType name="Balise">
		<xs:sequence>
			<xs:element name="etcsPackets" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="etcsPacket" type="ss026:BalisePacket" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="fixed" type="xs:boolean" use="required"/>
		<xs:attribute name="m_dup" type="eng:DuplicationType" use="required"/>
		<xs:attribute name="m_mcount" type="xs:unsignedInt" use="required"/>
		<xs:attribute name="n_pig" type="xs:unsignedInt" use="required"/>
		<xs:attribute name="verticallyOriented" type="xs:boolean" use="required"/>
		<xs:attribute name="standardSize" type="xs:boolean" use="required"/>
		<xs:attribute name="telegram" type="xs:base64Binary" use="required"/>
		<xs:attribute name="telegramChecksum" type="xs:string" use="required"/>
		<xs:attribute name="sleeperFastening" type="xs:string" use="required"/>
		<xs:attribute name="baliseMountingSystem" type="xs:string" use="required"/>
		<xs:attribute name="designType" type="xs:string" use="required"/>
		<xs:attribute name="kmReferenceMarker" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Reference to eng:KmSign</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="balise" type="eng:Balise"/>
	<xs:complexType name="Sleepers">
		<xs:sequence>
			<xs:element name="trackEdgeSection" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="trackEdgeSectionItem" type="infra:TrackEdgeSection" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="sleepersType" type="eng:SleepersType" use="required"/>
	</xs:complexType>
	<xs:element name="sleepers" type="eng:Sleepers"/>
	<xs:complexType name="DangerPoint">
		<xs:sequence>
			<xs:element name="spotLocation" type="infra:TrackEdgePoint" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="dangerPoint" type="eng:DangerPoint"/>
	<xs:complexType name="FoulingPoint">
		<xs:sequence>
			<xs:element name="spotLocation" type="infra:TrackEdgePoint" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="clearancePoint" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="foulingPoint" type="eng:FoulingPoint"/>
	<xs:complexType name="EngArea">
		<xs:sequence>
			<xs:element name="simplePoints" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="simplePoint" type="eng:SimplePoint" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="crossings" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="crossing" type="eng:Crossing" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="levelCrossings" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="levelCrossing" type="eng:LevelCrossing" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="baliseGroup" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="baliseGroupItem" type="eng:BaliseGroup" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="balises" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="balise" type="eng:Balise" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="sleepers" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="sleeper" type="eng:Sleepers" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="dangerPoints" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dangerPoint" type="eng:DangerPoint" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="foulingPoints" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="foulingPoint" type="eng:FoulingPoint" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="bufferStops" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="bufferStop" type="eng:BufferStop" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="defaultSleepersType" type="eng:SleepersType" use="required"/>
	</xs:complexType>
	<xs:element name="engArea" type="eng:EngArea"/>
	<xs:complexType name="LocationAccuracyArea">
		<xs:sequence>
			<xs:element name="baliseAccuracies" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="baliseAccuracy" type="eng:BaliseAccuracy" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="etcsMarkerAccuracies" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="etcsMarkerAccuracy" type="eng:EtcsMarkerAccuracy" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="stopLocationAccuracies" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="stopLocationAccuracy" type="eng:StopLocationAccuracy" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="nationalBorderAccuracies" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nationalBorderAccuracy" type="eng:NationalBorderAccuracy" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="bufferStopAccuracies" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="bufferStopAccuracy" type="eng:BufferStopAccuracy" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="locationAccuracyArea" type="eng:LocationAccuracyArea"/>
	<xs:complexType name="BaliseAccuracy">
		<xs:sequence/>
		<xs:attribute name="baliseId" type="xs:string" use="required"/>
		<xs:attribute name="accuracy" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="baliseAccuracy" type="eng:BaliseAccuracy"/>
	<xs:complexType name="EtcsMarkerAccuracy">
		<xs:sequence/>
		<xs:attribute name="markerId" type="xs:string" use="required"/>
		<xs:attribute name="accuracy" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="etcsMarkerAccuracy" type="eng:EtcsMarkerAccuracy"/>
	<xs:complexType name="StopLocationAccuracy">
		<xs:sequence/>
		<xs:attribute name="stopLocationId" type="xs:string" use="required"/>
		<xs:attribute name="accuracy" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="stopLocationAccuracy" type="eng:StopLocationAccuracy"/>
	<xs:complexType name="NationalBorderAccuracy">
		<xs:sequence/>
		<xs:attribute name="nationalBorderId" type="xs:string" use="required"/>
		<xs:attribute name="accuracy" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="nationalBorderAccuracy" type="eng:NationalBorderAccuracy"/>
	<xs:complexType name="BufferStopAccuracy">
		<xs:sequence/>
		<xs:attribute name="bufferStopId" type="xs:string" use="required"/>
		<xs:attribute name="accuracy" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="bufferStopAccuracy" type="eng:BufferStopAccuracy"/>
	<xs:complexType name="TrackEdgeKmSigns">
		<xs:sequence>
			<xs:element name="kmSigns" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="kmSign" type="eng:KmSign" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="trackEdgeKmSigns" type="eng:TrackEdgeKmSigns"/>
	<xs:complexType name="KmSign">
		<xs:sequence/>
		<xs:attribute name="pos" type="xs:unsignedInt" use="required"/>
		<xs:attribute name="label" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="kmSign" type="eng:KmSign"/>
	<xs:complexType name="KmArea">
		<xs:sequence>
			<xs:element name="trackEdgeKmSigns" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="trackEdgeKmSign" type="eng:TrackEdgeKmSigns" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="kmArea" type="eng:KmArea"/>
	<xs:complexType name="ETCSEngineering">
		<xs:sequence>
			<xs:element name="engAreas" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="engArea" type="eng:EngArea" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="locationAccuracyAreas" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="locationAccuracyArea" type="eng:LocationAccuracyArea" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="kmAreas" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="kmArea" type="eng:KmArea" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="eTCSEngineering" type="eng:ETCSEngineering"/>
</xs:schema>

=== UICrail/SemanticRSM/Source_data/scheibenberg/eng_v0.4.2.xml
<?xml version="1.0" encoding="utf-8"?>
<engArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="3c301633-c819-423d-b783-19c7ff48780e"
  defaultSleepersType="unknownSleepersType" xmlns="https://erju.org/eng"
  xsi:schemaLocation="https://erju.org/eng eng.xsd">
  <simplePoints>
    <simplePoint id="W1" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W1 Fouling Point Left" />
        <foulingPoint ref="W1 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
    <simplePoint id="W6" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W6 Fouling Point Left" />
        <foulingPoint ref="W6 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
    <simplePoint id="W7" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W7 Fouling Point Left" />
        <foulingPoint ref="W7 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
    <simplePoint id="W9" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W9 Fouling Point Left" />
        <foulingPoint ref="W9 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
    <simplePoint id="W10" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W10 Fouling Point Left" />
        <foulingPoint ref="W10 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
    <simplePoint id="W21" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W21 Fouling Point Left" />
        <foulingPoint ref="W21 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
    <simplePoint id="W22" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W22 Fouling Point Left" />
        <foulingPoint ref="W22 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
    <simplePoint id="W11" tipShift="0" bladeLength="0">
      <foulingPoints>
        <foulingPoint ref="W11 Fouling Point Left" />
        <foulingPoint ref="W11 Fouling Point Right" />
      </foulingPoints>
    </simplePoint>
  </simplePoints>
  <foulingPoints>
    <foulingPoint id="W1 Fouling Point Left" name="W1 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([Main],10470.643)-&gt;([Main],10822.043)]" pos="44645"
      />
    </foulingPoint>
    <foulingPoint id="W1 Fouling Point Right" name="W1 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([3],0.000)-&gt;([3],518.233)]" pos="44682"
      />
    </foulingPoint>
    <foulingPoint id="W6 Fouling Point Left" name="W6 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([6-1],0.000)-&gt;([6-1],36.217)]" pos="31593"
      />
    </foulingPoint>
    <foulingPoint id="W6 Fouling Point Right" name="W6 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([1],217.828)-&gt;([1],388.653)]" pos="31593"
      />
    </foulingPoint>
    <foulingPoint id="W7 Fouling Point Left" name="W7 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([6-1],0.000)-&gt;([6-1],36.217)]" pos="4625"
      />
    </foulingPoint>
    <foulingPoint id="W7 Fouling Point Right" name="W7 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([6],0.000)-&gt;([6],118.521)]" pos="86929"
      />
    </foulingPoint>
    <foulingPoint id="W9 Fouling Point Left" name="W9 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([1],217.828)-&gt;([1],388.653)]" pos="90977"
      />
    </foulingPoint>
    <foulingPoint id="W9 Fouling Point Right" name="W9 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([6],118.521)-&gt;([6],254.457)]" pos="55129"
      />
    </foulingPoint>
    <foulingPoint id="W10 Fouling Point Left" name="W10 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([Main],10470.643)-&gt;([Main],10822.043)]" pos="319437"
      />
    </foulingPoint>
    <foulingPoint id="W10 Fouling Point Right" name="W10 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([6],254.457)-&gt;([6],295.524)]" pos="8996"
      />
    </foulingPoint>
    <foulingPoint id="W21 Fouling Point Left" name="W21 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([3],518.233)-&gt;([3],1394.082)]" pos="31971"
      />
    </foulingPoint>
    <foulingPoint id="W21 Fouling Point Right" name="W21 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([21],0.000)-&gt;([21],109.560)]" pos="27969"
      />
    </foulingPoint>
    <foulingPoint id="W22 Fouling Point Left" name="W22 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([21],109.560)-&gt;([21],6366.940)]" pos="32575"
      />
    </foulingPoint>
    <foulingPoint id="W22 Fouling Point Right" name="W22 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([22],0.000)-&gt;([22],2757.878)]" pos="32575"
      />
    </foulingPoint>
    <foulingPoint id="W11 Fouling Point Left" name="W11 Fouling Point Left" clearancePoint="0">
      <spotLocation trackEdge="[([3],518.233)-&gt;([3],1394.082)]" pos="819338"
      />
    </foulingPoint>
    <foulingPoint id="W11 Fouling Point Right" name="W11 Fouling Point Right" clearancePoint="0">
      <spotLocation trackEdge="[([Main],10822.043)-&gt;([Main],11846.159)]" pos="971642"
      />
    </foulingPoint>
    <foulingPoint id="b68590d9-95af-49e3-84fd-21e91a1a9545" name="Prb.fest. BufferStop"
      clearancePoint="0">
      <spotLocation trackEdge="[([6],0.000)-&gt;([6],118.521)]" pos="4000"
      />
    </foulingPoint>
    <foulingPoint id="5ce79d55-b2e9-4396-8d19-311c67d61af1" name="Prb.fest. BufferStop"
      clearancePoint="0">
      <spotLocation trackEdge="[([1],0.000)-&gt;([1],217.828)]" pos="42"
      />
    </foulingPoint>
    <foulingPoint id="d62e0253-a1ca-48f0-a0ca-b28c5e0e1fe0" name="Prb.fest. BufferStop"
      clearancePoint="0">
      <spotLocation trackEdge="[([22],0.000)-&gt;([22],2757.878)]" pos="2757878"
      />
    </foulingPoint>
    <foulingPoint id="56bd742e-5b79-468c-b9e2-38089c406b49" name="Prb.fest. BufferStop"
      clearancePoint="0">
      <spotLocation trackEdge="[([21],109.560)-&gt;([21],6366.940)]" pos="6257380"
      />
    </foulingPoint>
  </foulingPoints>
</engArea>

=== UICrail/SemanticRSM/Source_data/Scheibenberg-1.0-MBD-0.3/eng_v1.0.xml
<?xml version="1.0" encoding="utf-8"?>
<eTCSEngineering xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="https://erju.org/eng"
  xsi:schemaLocation="https://erju.org/eng eng.xsd">
  <engAreas>
    <engArea id="cc895b50-d90e-4a6c-8c9b-0c85b8253a13" defaultSleepersType="unknownSleepersType">
      <simplePoints>
        <simplePoint id="DEDEMIPDRPOI27##0001" tipShift="1" bladeLength="3">
          <foulingPoints>
            <foulingPoint ref="W1 Fouling Point Left" />
            <foulingPoint ref="W1 Fouling Point Right" />
          </foulingPoints>
        </simplePoint>
        <simplePoint id="DEDEMIPDRPOI27##0002" tipShift="1" bladeLength="3">
          <foulingPoints>
            <foulingPoint ref="W6 Fouling Point Left"/>
            <foulingPoint ref="W6 Fouling Point Right"/>
          </foulingPoints>
        </simplePoint>
        <simplePoint id="DEDEMIPDRPOI27##0003" tipShift="1" bladeLength="3">
          <foulingPoints>
            <foulingPoint ref="W7 Fouling Point Left" />
            <foulingPoint ref="W7 Fouling Point Right" />
          </foulingPoints>
        </simplePoint>
        <simplePoint id="DEDEMIPDRPOI27##0004" tipShift="1" bladeLength="3">
          <foulingPoints>
            <foulingPoint ref="W9 Fouling Point Left" />
            <foulingPoint ref="W9 Fouling Point Right" />
          </foulingPoints>
        </simplePoint>
        <simplePoint id="DEDEMIPDRPOI27##0005" tipShift="1" bladeLength="3">
          <foulingPoints>
            <foulingPoint ref="W10 Fouling Point Left" />
            <foulingPoint ref="W10 Fouling Point Right" />
          </foulingPoints>
        </simplePoint>
        <simplePoint id="DEDEMIPDRPOI27##0006" tipShift="1" bladeLength="3">
          <foulingPoints>
            <foulingPoint ref="W11 Fouling Point Left" />
            <foulingPoint ref="W11 Fouling Point Right" />
          </foulingPoints>
        </simplePoint>
      </simplePoints>
      <crossings />
      <levelCrossings />
      <baliseGroup />
      <balises />
      <sleepers />
      <dangerPoints />
      <foulingPoints>
        <foulingPoint id="W1 Fouling Point Left" name="W1 Fouling Point Left" clearancePoint="0">
          <spotLocation trackEdge="T2 _ W1 ]-[ W10" pos="44645" />
        </foulingPoint>
        <foulingPoint id="W1 Fouling Point Right" name="W1 Fouling Point Right" clearancePoint="0">
          <spotLocation trackEdge="T11 _ W1 ]-[ W11" pos="44682" />
        </foulingPoint>
        <foulingPoint id="W6 Fouling Point Left" name="W6 Fouling Point Left" clearancePoint="0">
          <spotLocation trackEdge="T10 _ W6 ]-[ W7" pos="31593" />
        </foulingPoint>
        <foulingPoint id="W6 Fouling Point Right" name="W6 Fouling Point Right" clearancePoint="0">
          <spotLocation trackEdge="T9 _ W6 ]-[ W9" pos="31593" />
        </foulingPoint>
        <foulingPoint id="W7 Fouling Point Left" name="W7 Fouling Point Left" clearancePoint="0">
          <spotLocation trackEdge="T10 _ W6 ]-[ W7" pos="4625" />
        </foulingPoint>
        <foulingPoint id="W7 Fouling Point Right" name="W7 Fouling Point Right" clearancePoint="0">
          <spotLocation trackEdge="T5 _ W7 ]-[ " pos="86929" />
        </foulingPoint>
        <foulingPoint id="W9 Fouling Point Left" name="W9 Fouling Point Left" clearancePoint="0">
          <spotLocation trackEdge="T9 _ W6 ]-[ W9" pos="90977" />
        </foulingPoint>
        <foulingPoint id="W9 Fouling Point Right" name="W9 Fouling Point Right" clearancePoint="0">
          <spotLocation trackEdge="T6 _ W7 ]-[ W9" pos="55129" />
        </foulingPoint>
        <foulingPoint id="W10 Fouling Point Left" name="W10 Fouling Point Left" clearancePoint="0">
          <spotLocation trackEdge="T2 _ W1 ]-[ W10" pos="319437" />
        </foulingPoint>
        <foulingPoint id="W10 Fouling Point Right" name="W10 Fouling Point Right" clearancePoint="0">
          <spotLocation trackEdge="T7 _ W9 ]-[ W10" pos="8996" />
        </foulingPoint>
        <foulingPoint id="W11 Fouling Point Left" name="W11 Fouling Point Left" clearancePoint="0">
          <spotLocation trackEdge="T11 _ W1 ]-[ W11" pos="1337571" />
        </foulingPoint>
        <foulingPoint id="W11 Fouling Point Right" name="W11 Fouling Point Right" clearancePoint="0">
          <spotLocation trackEdge="T3 _ W10 ]-[ W11" pos="971642" />
        </foulingPoint>
        <foulingPoint id="for Buffer on T5 _ W7 ]-[ " name="Prb.fest. BufferStop" clearancePoint="0">
          <spotLocation trackEdge="T5 _ W7 ]-[ " pos="4000" />
        </foulingPoint>
        <foulingPoint id="for Buffer on T8 _ W6 ]-[ " name="Prb.fest. BufferStop" clearancePoint="0">
          <spotLocation trackEdge="T8 _ W6 ]-[ " pos="42" />
        </foulingPoint>
      </foulingPoints>
      <bufferStops />
    </engArea>
  </engAreas>
</eTCSEngineering>
