=== UICrail/SemanticRSM/Source_data/scheibenberg/tp.xsd
<?xml version="1.0" ?>
<xs:schema targetNamespace="https://erju.org/tp" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tp="https://erju.org/tp" elementFormDefault="qualified" xmlns:infra="https://erju.org/infra" xmlns:ss026="https://erju.org/ss026">
	<xs:import namespace="https://erju.org/infra" schemaLocation="infra.xsd"/>
	<xs:import namespace="https://erju.org/ss026" schemaLocation="ss026.xsd"/>
	<xs:simpleType name="DPSDependencyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Exclusive"/>
			<xs:enumeration value="Equivalent"/>
			<xs:enumeration value="Specific"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ProtectedInfraElement">
		<xs:choice>
			<xs:element name="simplePoint">
				<xs:complexType>
					<xs:attribute name="ref" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="slipCrossing">
				<xs:complexType>
					<xs:attribute name="ref" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="crossing">
				<xs:complexType>
					<xs:attribute name="ref" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="derailer">
				<xs:complexType>
					<xs:attribute name="ref" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="levelCrossing">
				<xs:complexType>
					<xs:attribute name="ref" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="DriveProtectionSectionGroup">
		<xs:sequence>
			<xs:element name="driveProtectionSections" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="driveProtectionSection" type="tp:DriveProtectionSection" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="protectedInfraElements" type="tp:ProtectedInfraElement" minOccurs="1" maxOccurs="1"/>
			<xs:element name="dpsgDependencies" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dpsgDependency" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="value" type="xs:unsignedInt" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="dependenciesType" type="tp:DPSDependencyType" use="required"/>
		<xs:attribute name="runTime" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="driveProtectionSectionGroup" type="tp:DriveProtectionSectionGroup"/>
	<xs:complexType name="DriveProtectionSection">
		<xs:sequence>
			<xs:element name="trackEdgeSection" type="infra:TrackEdgeSection" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="maxFlankProtectionSpeed" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="driveProtectionSection" type="tp:DriveProtectionSection"/>
	<xs:complexType name="AllocationSection">
		<xs:sequence>
			<xs:element name="linearLocation" type="infra:LinkedPath" minOccurs="1" maxOccurs="1"/>
			<xs:element name="dependencies" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to tp:AllocationSection</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dependency" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="allocationSection" type="tp:AllocationSection"/>
	<xs:complexType name="ControlledInfraElement">
		<xs:choice>
			<xs:element name="dpsGroup">
				<xs:complexType>
					<xs:attribute name="ref" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="tvpSection">
				<xs:complexType>
					<xs:attribute name="ref" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="FieldObjectController">
		<xs:sequence>
			<xs:element name="controlledInfraElements" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="controlledInfraElement" type="tp:ControlledInfraElement" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="rastaServerId" type="xs:string" use="required"/>
		<xs:attribute name="rastaOCId" type="xs:string" use="required"/>
		<xs:attribute name="version" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:element name="fieldObjectController" type="tp:FieldObjectController"/>
	<xs:complexType name="Route">
		<xs:sequence>
			<xs:element name="pointsToRight" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to infra:SimplePoint</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="pointsToRightItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="pointsToLeft" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to infra:SimplePoint</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="pointsToLeftItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="route" type="tp:Route"/>
	<xs:complexType name="SimplePoint">
		<xs:sequence>
			<xs:element name="routeRequiresPointRight" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to tp:Route</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="routeRequiresPointRightItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="routeRequiresPointLeft" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to tp:Route</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="routeRequiresPointLeftItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="transitLockingPointRight" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to tp:Transit</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="transitLockingPointRightItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="transitLockingPointLeft" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to tp:Transit</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="transitLockingPointLeftItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="zoneLockingPointRight" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to infra:TvpSection</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="zoneLockingPointRightItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="zoneLockingPointLeft" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to infra:TvpSection</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="zoneLockingPointLeftItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="simplePoint" type="tp:SimplePoint"/>
	<xs:complexType name="Transit">
		<xs:sequence>
			<xs:element name="transitZone" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to infra:TvpSection</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="transitZoneItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="routeRequestingTransit" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Reference to tp:Route</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="routeRequestingTransitItem" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="upstreamTransits" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="transit" type="tp:Transit"/>
	<xs:complexType name="TrainProtectionArea">
		<xs:sequence>
			<xs:element name="dpsGroups" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dpsGroup" type="tp:DriveProtectionSectionGroup" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="allocationSections" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="allocationSection" type="tp:AllocationSection" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="fieldObjectControllers" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="fieldObjectController" type="tp:FieldObjectController" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="routes" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="route" type="tp:Route" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="simplePoints" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="simplePoint" type="tp:SimplePoint" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="transits" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="transit" type="tp:Transit" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="trainProtectionArea" type="tp:TrainProtectionArea"/>
	<xs:complexType name="TrainProtection">
		<xs:sequence>
			<xs:element name="tpArea" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="tpAreaItem" type="tp:TrainProtectionArea" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="trainProtection" type="tp:TrainProtection"/>
</xs:schema>

=== UICrail/SemanticRSM/Source_data/scheibenberg/tp_v0.4.2.xml
<?xml version="1.0" encoding="utf-8"?>
<trainProtectionArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="3c301633-c819-423d-b783-19c7ff48780e"
  xmlns="https://erju.org/tp"
  xsi:schemaLocation="https://erju.org/tp tp.xsd">
  <dpsGroups>
    <dpsGroup id="b45c0557-d710-42e3-95ec-5716eec9d5ba" name="DPSG_W1" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="46dce768-c86b-4136-b9e2-7953a90af389"
          name="DPS_b45c0557-d710-42e3-95ec-5716eec9d5ba" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([Main],10470.643)-&gt;([Main],10822.043)]"
            skipFromStart="1000" skipFromEnd="347401" />
        </driveProtectionSection>
        <driveProtectionSection id="adea42fa-31b3-4483-b5a2-0b306c414e63"
          name="DPS_b45c0557-d710-42e3-95ec-5716eec9d5ba" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([3],0.000)-&gt;([3],518.233)]" skipFromStart="1000"
            skipFromEnd="514233" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W1" />
      </protectedInfraElements>
    </dpsGroup>
    <dpsGroup id="ece72d3b-c487-4817-b81c-8b483c176a72" name="DPSG_W6" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="6c5264fc-e3b3-412f-b48c-75e447d57cd2"
          name="DPS_ece72d3b-c487-4817-b81c-8b483c176a72" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([1],217.828)-&gt;([1],388.653)]" skipFromStart="1000"
            skipFromEnd="166825" />
        </driveProtectionSection>
        <driveProtectionSection id="44947a8a-cb7e-4694-afa6-22981e476ec8"
          name="DPS_ece72d3b-c487-4817-b81c-8b483c176a72" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([6-1],0.000)-&gt;([6-1],36.217)]" skipFromStart="1000"
            skipFromEnd="32217" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W6" />
      </protectedInfraElements>

    </dpsGroup>
    <dpsGroup id="b9dcf641-4165-4961-ac6a-4914fdf107c9" name="DPSG_W7" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="582db38a-7025-4db6-8e06-d19644afc41a"
          name="DPS_b9dcf641-4165-4961-ac6a-4914fdf107c9" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([6],0.000)-&gt;([6],118.521)]" skipFromStart="114521"
            skipFromEnd="1000" />
        </driveProtectionSection>
        <driveProtectionSection id="8a8230f4-deb0-4e2b-a448-26a44bc00f0d"
          name="DPS_b9dcf641-4165-4961-ac6a-4914fdf107c9" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([6-1],0.000)-&gt;([6-1],36.217)]" skipFromStart="32217"
            skipFromEnd="1000" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W7" />
      </protectedInfraElements>

    </dpsGroup>
    <dpsGroup id="e0c1121b-f097-4fd9-ab14-1505c78aaef5" name="DPSG_W9" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="b9fec0d7-1320-47a2-871f-0c723e515272"
          name="DPS_e0c1121b-f097-4fd9-ab14-1505c78aaef5" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([6],118.521)-&gt;([6],254.457)]" skipFromStart="131936"
            skipFromEnd="1000" />
        </driveProtectionSection>
        <driveProtectionSection id="2f792c5b-10d9-4a71-9991-7472ec30bb37"
          name="DPS_e0c1121b-f097-4fd9-ab14-1505c78aaef5" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([1],217.828)-&gt;([1],388.653)]" skipFromStart="166825"
            skipFromEnd="1000" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W9" />
      </protectedInfraElements>

    </dpsGroup>
    <dpsGroup id="894549e2-0709-461b-a05a-5b3c899ede45" name="DPSG_W10" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="c1e71e07-d017-45cb-954e-db7e9e7309a3"
          name="DPS_894549e2-0709-461b-a05a-5b3c899ede45" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([Main],10470.643)-&gt;([Main],10822.043)]"
            skipFromStart="347401" skipFromEnd="1000" />
        </driveProtectionSection>
        <driveProtectionSection id="411fa43e-b213-41ac-b30a-3df4067a4a8e"
          name="DPS_894549e2-0709-461b-a05a-5b3c899ede45" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([6],254.457)-&gt;([6],295.524)]" skipFromStart="37066"
            skipFromEnd="1000" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W10" />
      </protectedInfraElements>

    </dpsGroup>
    <dpsGroup id="02e63eea-b26e-41bd-8732-083754910e43" name="DPSG_W21" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="5d38b1f2-7850-47ff-8448-1a53f243c25d"
          name="DPS_02e63eea-b26e-41bd-8732-083754910e43" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([3],518.233)-&gt;([3],1394.082)]" skipFromStart="1000"
            skipFromEnd="871850" />
        </driveProtectionSection>
        <driveProtectionSection id="d0271aa4-3b48-4560-9b9f-c6e318c546c9"
          name="DPS_02e63eea-b26e-41bd-8732-083754910e43" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([21],0.000)-&gt;([21],109.560)]" skipFromStart="1000"
            skipFromEnd="105560" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W21" />
      </protectedInfraElements>

    </dpsGroup>
    <dpsGroup id="df3b18c9-d182-4679-afe9-1cb96b0dc5bd" name="DPSG_W22" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="62bee305-3c5a-4ad0-94c3-f6315a5cd419"
          name="DPS_df3b18c9-d182-4679-afe9-1cb96b0dc5bd" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([21],109.560)-&gt;([21],6366.940)]" skipFromStart="1000"
            skipFromEnd="6253380" />
        </driveProtectionSection>
        <driveProtectionSection id="f23bbece-4597-4036-83cd-f26e14d34ec2"
          name="DPS_df3b18c9-d182-4679-afe9-1cb96b0dc5bd" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([22],0.000)-&gt;([22],2757.878)]" skipFromStart="1000"
            skipFromEnd="2753878" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W22" />
      </protectedInfraElements>

    </dpsGroup>
    <dpsGroup id="a92cad58-95e3-44dc-bb6f-ca2ac6a0aea4" name="DPSG_W11" dependenciesType="Exclusive"
      runTime="0">
      <driveProtectionSections>
        <driveProtectionSection id="0097ccca-2b5f-4f7e-973f-2e2cadfb8201"
          name="DPS_a92cad58-95e3-44dc-bb6f-ca2ac6a0aea4" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([Main],10822.043)-&gt;([Main],11846.159)]"
            skipFromStart="1020116" skipFromEnd="1000" />
        </driveProtectionSection>
        <driveProtectionSection id="47dcd553-ee32-465a-888f-0f3f75b675e7"
          name="DPS_a92cad58-95e3-44dc-bb6f-ca2ac6a0aea4" maxFlankProtectionSpeed="0">
          <trackEdgeSection trackEdge="[([3],518.233)-&gt;([3],1394.082)]" skipFromStart="871850"
            skipFromEnd="1000" />
        </driveProtectionSection>
      </driveProtectionSections>
      <protectedInfraElements>
        <simplePoint ref="W11" />
      </protectedInfraElements>

    </dpsGroup>
  </dpsGroups>
  <allocationSections>
    <allocationSection id="f955607e-1f4c-4a11-b509-0715d0182377" name="AS_W1">
      <linearLocation skipFromPathStart="0" skipFromPathEnd="306756">
        <dirTrackEdges xmlns="https://erju.org/infra">
          <dirTrackEdge trackEdge="[([Main],10470.643)-&gt;([Main],10822.043)]" sameDir="true" />
        </dirTrackEdges>
      </linearLocation>
      <dependencies>
        <dependency ref="b07846b1-9b6a-4af5-bfda-7c32dffa67ca" />
      </dependencies>
    </allocationSection>
    <allocationSection id="b07846b1-9b6a-4af5-bfda-7c32dffa67ca" name="AS_W1">
      <linearLocation skipFromPathStart="0" skipFromPathEnd="473551">
        <dirTrackEdges xmlns="https://erju.org/infra">
          <dirTrackEdge trackEdge="[([3],0.000)-&gt;([3],518.233)]" sameDir="true" />
        </dirTrackEdges>
      </linearLocation>
      <dependencies>
        <dependency ref="f955607e-1f4c-4a11-b509-0715d0182377" />
      </dependencies>
    </allocationSection>
    <allocationSection id="57ab78d5-a8e6-4f0b-9c6c-fd95a23523a3" name="AS_W6">
      <linearLocation skipFromPathStart="0" skipFromPathEnd="139232">
        <dirTrackEdges xmlns="https://erju.org/infra">
          <dirTrackEdge trackEdge="[([1],217.828)-&gt;([1],388.653)]" sameDir="true" />
        </dirTrackEdges>
      </linearLocation>
      <dependencies>
        <dependency ref="7f6ff523-f902-465a-973d-ca5a98326c3c" />
      </dependencies>
    </allocationSection>
    <allocationSection id="7f6ff523-f902-465a-973d-ca5a98326c3c" name="AS_W6">
      <linearLocation skipFromPathStart="0" skipFromPathEnd="4624">
        <dirTrackEdges xmlns="https://erju.org/infra">
          <dirTrackEdge trackEdge="[([6-1],0.000)-&gt;([6-1],36.217)]" sameDir="true" />
        </dirTrackEdges>
      </linearLocation>
      <dependencies>
        <dependency ref="57ab78d5-a8e6-4f0b-9c6c-fd95a23523a3" />
      </dependencies>
    </allocationSection>
    <allocationSection id="535d1e11-17e3-47a0-a012-f927074dc653" name="AS_W7">
